# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "RECOMB-Seq Workshop"
email: "calkan@gmail.com"
description: "RECOMB-Seq is the RECOMB Satellite Conference on Biological Sequence Analysis"
baseurl: ""
url: "https://recomb-seq.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: "recomb-seq.github.io"
siteVerification: ""

# Organizer Info
organizerName: "RECOMB-Seq"
organizerAlternateName: "RECOMB-Seq"
organizerDescription: "Algorithm development for analyzing sequence data"
organizerEmail: "calkan@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.alkanlab.org"

# Head
metaKeywords: "recomb, algorithm, sequence"
twitterAccount: "@recombseq"
# socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/papers/", text: "Call for contributions"}
 - {permalink: "/team/", text: "Committees"}
 - {permalink: "/speakers/", text: "Keynote Speakers"}
 - {permalink: "/program/", text: "Program"}
 - {permalink: "/history/", text: "History of RECOMB SEQ"}
bottomNavigationLinks:
# - {link: "https://bit.ly/dfua-c4p", text: "Submit a paper"}
rightNavigationButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Submit a paper"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "RECOMB-SEQ 2023"
heroSubTitle: "The 13th RECOMB Satellite Conference on Biological Sequence Analysis"
eventDate: "April 2023"
eventLocation: "Ä°stanbul, Turkey"
#typeoutTextValues: '"2023"'
#typeoutFallback: "2023"
heroButtons:
 #- {link: "https://bit.ly/dfua-c4p", text: "Submit a paper"}
 #- {permalink: "/#tickets", text: "Attend RECOMB SEQ 2023"}

# About Block
aboutTitle: "About RECOMB SEQ"
# aboutBlock:
# - {title: "RECOMB-SEQ", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
# - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
# - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "TBD"
eventLocationLink: "TBD"
eventStreetAddress: "TBD"
eventAddressLocality: ""
eventAddressLocalityRegion: "Istanbul"
eventPostalCode: ""
eventAddressCountry: "Turkey"
eventStartTime: "2022-10-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2022-10-25T20:00"
eventPlaceCoordinates: "41.0053215,29.0121795"
mapCenterCoordinates: "41.0053215,29.0121795"
mapMobileCenterCoordinates: "41.0053215,29.0121795"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "TBD"
venueFeatures: [""]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "recombseq"
twitterFeed: " https://twitter.com/recombseq"


# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/recombseq", icon: "twitter"}
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {link: "https://www.youtube.com/channel/UCYdQZ9egzBoszApB4ksjE3g/playlists", icon: "youtube"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
  # - {link: "https://recomb2022.net", text: "RECOMB 2022"}
 -
  # title: "Contacts"
  # links:
  # - {link: "mailto:christinaboucher@ufl.edu", text: "christinaboucher@ufl.edu"}
 -
  title: "Policies"
  links:
   - {permalink: "/coi/", text: "Conflict-of-interest Policy"}
   # - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Collections
collections:
  paper-calls:
    output: true
# Speakers List Block
showSessions: false

# Team Block
#teamBlockTitle: "About us"
#aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

